server:
  id: "manager-01"
  port: 8823 # default: 8823
  type: "manager" # default: single
data:
  path: "/mnt/sda1"
shard:
  rules:
    - id: "shard-01"
      conditions:
        - "ns:2;nodename[a-fA-F].*[0-5]+$"
        - "ns:2;nodename[a-fA-F].*[a-z8]+$"
    - id: "shard-02"
      conditions:
        - "ns:2;nodename[g-zG-Z].*[0-5]+$"
        - "ns:2;nodename[g-zG-Z].*[a-z8]+$"

server:
  id: "shard-01"
  port: 18823
  type: "shard" 
  manager:
    host: 192.168.0.22
    port: 8823
storage: # tj
  hot:
    duration: 90     # 90일
    path: "/mnt/ssd" 
  cold:
    path: "/mnt/hdd"
    compress: true 

server:
  id: "db-01"
  port: 8823
data:
  path: "/mnt/sda1"